### ISSUE TITLE
Commission Request: Update for v11

### ISSUE THREAD

**Issue by pixel7777** [zeel01/poi-teleport#18]
I am interested in commissioning an update for this module to ensure it's compatbility with v11 and Monk's Enhanced Journal.  You can find me on Discord at pixel7777 or email me at heidijugovic@gmail.com.

**Comment by zeel01** [comment]
Hey there, I *am* intending to get this updated for v11/12 eventually though I don't have a timeline for that. I'm not sure about Monk's Enhanced Journal support though, that will depend on how simple/complex it is to ensure that it works.

That being said, I'm not currently accepting commissions so while I am planning to update this I don't need compensated (and I also can't guarantee how soon).

I *am* open to reviewing Pull Requests from other contributors, and I don't mind if they're being commissioned to do so. However in the event that someone is commissioned to updated this, I must still approve of the changes and I am not liable financially if the changes are not acceptable or if it takes a while for me to review them, nor will I be able to compensate the contributor in the case of non-payment for any reason - all financial agreements are between the commissioner and the contributor.

If you would like to proceed with finding someone to help update this before I have a chance to do so myself, I would recommend posting your request on the League of Extraordinary Foundry VTT Developers Discord server: https://discord.gg/AKQsDTfS48

I'm going to close this issue and open two new issues in its place, one for v11 support (#19) and one for Monk's Enhanced Journal compatibility (#20). Pull Requests should reference those issues, and ideally these two changes should be separate PRs unless one of them proves to be trivial.
