### ISSUE TITLE
[Feature] Public name of POI

### ISSUE THREAD

**Issue by lozalojo** [zeel01/poi-teleport#5]
First: great work!

Currently, If I’ve understood the module right, the process is at follows:

Create journal entry for a location, let’s say “House of Nayara”, dragndrop as a POI in a map and share to the players.

The players will see in their map an icon for “House of Nayara” and I, as GM, can click on the POI to teleport to the scene.

This requires to have defined the scene’s journal entry as the one shared with the players: “House of Nayara”.

The problem I’ve faced is that “House of Nayara” points to the scene “Zombies attack”, whose name for players is “Pleasant rest at Navara’s House”, and that scene has GM notes in another journal entry called also “Zombies attack”. I don’t want to use this journal GM entry as POI, I don’t want the players to see that text in the map.

So currently I have Journal entries for locations with general names and journal entries with GM notes associated to scenes, and the problem is that when I right click the scene at journal entry it shows the empty location journal, instead of the gm notes journal.

Not to duplicate journal entries I’d suggest:

Allow the name of the POI to be changed manually as “public name”, so that I can associate gm notes journal entry to the corresponding scene, dragndrop the journal to the map (“zombies attack”) and let edit the text to “House of Nayara”.
Or directly when dragndrop a journal which is associated to a scene use the “public players name” of the scene instead of the journal name.

Also, when there are two scenes associated to a location, do you set two different POIs? This is what I currently do, but the second one I set it to hidden and place next to the other for only me to see it as GM. Could it be managed more elegantly? Like a selector of scenes associated to that entry?

**Comment by zeel01** [comment]
So one of the primary design choices of this module, is simplicity. It leverages existing mechanics to add a bit more functionality, scenes can have notes, notes can be pinned on the map. I'm just adding a button to use that association to load the scene. I'm not likely to do much more than that. Journal name aliases, multiple journals for one scene... etc. These are out of scope for this module.

The best solution in this situation, would either be notes visible to the player as well as hidden notes for the GM only, or use a single journal entry with a player-facing title, and use GM secret blocks to hide GM notes about the zombies in the same entry. I like this technique, as it reduces the number of journals in the directory, and in most cases the player facing data is also of use to me. 

That being said, if someone were to create a module that allows for multiple journals per scene, or that allows you to alias the note name, I would be willing to look into supporting those features in conjunction with that module.

**Comment by lozalojo** [comment]
Another solution is to share POIs as "limited/observer" , the players wont see journal contents, no need to use GM notes for this.

Thanks
