### ISSUE TITLE
Linking pre-made journal entries with scenes

### ISSUE THREAD

**Issue by Arschev** [zeel01/poi-teleport#8]
If a journal entry is imported from another website (such as through the Kanka.io module), is it possible to link that imported entry to a scene? Any changes made on the Kanka campaign website are automatically updated in the foundry Journal and it would be a huge clutter reducer and qol change to not have 2 dedicated journal pages for any scene (such as city maps and secret bases)

**Comment by zeel01** [comment]
From the scene configuration panel, you can set the scene notes to any Journal Entry.

I do not know whether or not re-synchronizing the Journals with the external service will break this, you will have to test it. But you can certainly set the scene notes to any Journal Entry that you want.

**Comment by Arschev** [comment]
You're right, the note can link to any journal entry, but is there a way to have the note link to a scene?  

From what i understand, a scene is only linked to a journal entry if you right click the scene and click "create scene notes."  Otherwise, you cant activate a scene from the map note

**Comment by zeel01** [comment]
You can assign and Journal Entry to be the "scene notes" for a scene from
the scene configuration. Click on a scene in the sidebar to open the
config, and select the scene notes you want to associate with that scene
(all Journal Entries should be listed there).

If a map pin and a scene are both set to the same Journal Entry then POI
Teleporter will work.
